In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =pd.read_csv(r'C:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\data\medical_disease_prediction_10000.csv')

In [3]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [4]:
print(df.duplicated().sum())
print(df.isnull().sum())
# x=df.drop('Disease',axis=1)
# y=df[['Disease']]

0
Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [5]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [6]:
gender_dict ={'Male':0, 'Female':1}
df['Gender'] = df['Gender'].map(gender_dict)

In [7]:
df['Gender'].unique()

array([0, 1])

In [8]:
df['Smoking'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [9]:
smoking_dict ={'Yes':1, 'No':0}
df['Smoking'] = df['Smoking'].map(smoking_dict)

In [10]:
df['Smoking'].unique()

array([0, 1])

In [11]:
df['Alcohol'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [12]:
alcohol_dict ={'Yes':1, 'No':0}
df['Alcohol'] = df['Alcohol'].map(alcohol_dict)

In [13]:
df['Alcohol'].unique()

array([0, 1])

In [14]:
df['PhysicalActivity'].unique()

<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

In [15]:
physical_dict={'Medium': 1, 'High': 2, 'Low': 0}
df['PhysicalActivity'] = df['PhysicalActivity'].map(physical_dict)

In [16]:
df['PhysicalActivity'].unique()

array([1, 2, 0])

In [17]:
df['FamilyHistory'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [18]:
family_dict ={'Yes':1, 'No':0}
df['FamilyHistory'] = df['FamilyHistory'].map(family_dict)

In [19]:
df['FamilyHistory'].unique()

array([0, 1])

In [20]:
df['Disease'].unique()

<StringArray>
['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease', 'Diabetes']
Length: 5, dtype: str

In [21]:
disease_dict ={'Healthy':1, 'Pre-Diabetes':2, 'Hypertension':3, 'Heart Disease':4, 'Diabetes':5}
df['Disease']=df['Disease'].map(disease_dict)

In [22]:
df['Disease'].unique()

array([1, 2, 3, 4, 5])

In [23]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,0,17.5,102,177,161,88,0,0,1,0,1
1,69,0,31.1,118,256,147,92,0,0,2,1,2
2,61,1,31.3,114,206,193,74,1,0,1,0,1
3,47,1,23.9,105,162,253,68,0,0,0,0,1
4,47,0,28.3,148,121,280,84,0,1,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,0,27.1,177,183,268,59,0,0,2,0,3
9996,84,0,29.2,142,215,145,77,0,1,2,1,3
9997,41,0,22.8,177,265,133,71,0,0,1,1,3
9998,55,0,29.0,126,241,298,57,0,0,1,1,2
9999,59,0,32.2,151,162,225,93,0,0,2,1,2

In [24]:
x=df.drop('Disease',axis=1)
y=df[['Disease']]

In [25]:
x

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
0,23,0,17.5,102,177,161,88,0,0,1,0
1,69,0,31.1,118,256,147,92,0,0,2,1
2,61,1,31.3,114,206,193,74,1,0,1,0
3,47,1,23.9,105,162,253,68,0,0,0,0
4,47,0,28.3,148,121,280,84,0,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,49,0,27.1,177,183,268,59,0,0,2,0
9996,84,0,29.2,142,215,145,77,0,1,2,1
9997,41,0,22.8,177,265,133,71,0,0,1,1
9998,55,0,29.0,126,241,298,57,0,0,1,1
9999,59,0,32.2,151,162,225,93,0,0,2,1

In [26]:
y

      Disease
0           1
1           2
2           1
3           1
4           1
...       ...
9995        3
9996        3
9997        3
9998        2
9999        2

[10000 rows x 1 columns]

In [27]:
df.to_csv('cleaned_medical_disease_prediction.csv')